// ============================================
// REAL NASA DATA FOR ALL SOLAR SYSTEM BODIES
// Sources: NASA Planetary Fact Sheet, JPL
// ============================================

export const PLANET_INFO = {
  Sun: {
    name: "Sun",
    type: "Star",
    diameter: "1,391,000 km",
    mass: "1.989 × 10³⁰ kg",
    temperature: "5,500°C (surface)",
    age: "4.6 billion years",
    composition: "73% Hydrogen, 25% Helium",
    description: "The Sun is the star at the center of our Solar System. It is a nearly perfect ball of hot plasma, heated to incandescence by nuclear fusion reactions in its core. The Sun radiates energy mainly as visible light, ultraviolet, and infrared radiation.",
    facts: [
      "Contains 99.86% of the Solar System's mass",
      "Light takes 8 minutes 20 seconds to reach Earth",
      "Surface gravity is 28× Earth's gravity",
      "Core temperature reaches 15 million °C",
      "Produces energy equivalent to 100 billion nuclear bombs per second",
    ],
    moons: 0,
    hasRings: false,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "0 km (center)",
  },
  Mercury: {
    name: "Mercury",
    type: "Terrestrial Planet",
    diameter: "4,879 km",
    mass: "3.301 × 10²³ kg",
    temperature: "-180°C to 430°C",
    dayLength: "58.65 Earth days",
    yearLength: "87.97 Earth days",
    gravity: "3.7 m/s²",
    atmosphere: "Virtually none (exosphere)",
    description: "Mercury is the smallest planet in our Solar System and closest to the Sun. Its surface is heavily cratered and resembles Earth's Moon. Despite being closest to the Sun, it's not the hottest planet — that title goes to Venus.",
    facts: [
      "Smallest planet in the Solar System",
      "Has the most eccentric orbit of any planet",
      "No atmosphere means extreme temperature swings",
      "A day on Mercury lasts 59 Earth days",
      "Has a large iron core — 75% of its radius",
      "Surface covered in impact craters like the Moon",
    ],
    moons: 0,
    hasRings: false,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "57.9 million km",
  },
  Venus: {
    name: "Venus",
    type: "Terrestrial Planet",
    diameter: "12,104 km",
    mass: "4.867 × 10²⁴ kg",
    temperature: "462°C (average)",
    dayLength: "243 Earth days (retrograde)",
    yearLength: "224.7 Earth days",
    gravity: "8.87 m/s²",
    atmosphere: "96.5% CO₂, 3.5% Nitrogen",
    description: "Venus is the second planet from the Sun and the hottest planet in our Solar System. Its thick atmosphere traps heat in a runaway greenhouse effect. Venus rotates backwards compared to most planets.",
    facts: [
      "Hottest planet despite not being closest to Sun",
      "Rotates backwards (retrograde rotation)",
      "A day on Venus is longer than its year",
      "Surface pressure is 90× Earth's",
      "Often called Earth's 'sister planet' due to similar size",
      "Covered in thick sulfuric acid clouds",
    ],
    moons: 0,
    hasRings: false,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "108.2 million km",
  },
  Earth: {
    name: "Earth",
    type: "Terrestrial Planet",
    diameter: "12,742 km",
    mass: "5.972 × 10²⁴ kg",
    temperature: "15°C (average)",
    dayLength: "24 hours",
    yearLength: "365.25 days",
    gravity: "9.81 m/s²",
    atmosphere: "78% Nitrogen, 21% Oxygen",
    description: "Earth is the third planet from the Sun and the only known planet to harbor life. About 71% of its surface is covered in water. Earth's atmosphere and magnetic field protect life from harmful solar radiation.",
    facts: [
      "Only known planet with liquid water on the surface",
      "Has a powerful magnetic field from its iron core",
      "Atmosphere is 78% nitrogen, 21% oxygen",
      "Tilted 23.5° causing seasons",
      "Age: approximately 4.54 billion years",
      "The Moon stabilizes Earth's axial tilt",
    ],
    moons: 1,
    moonNames: ["Moon (Luna)"],
    hasRings: false,
    discoveredBy: "N/A",
    distanceFromSun: "149.6 million km (1 AU)",
  },
  Mars: {
    name: "Mars",
    type: "Terrestrial Planet",
    diameter: "6,779 km",
    mass: "6.417 × 10²³ kg",
    temperature: "-65°C (average)",
    dayLength: "24 hours 37 minutes",
    yearLength: "687 Earth days",
    gravity: "3.72 m/s²",
    atmosphere: "95.3% CO₂, 2.7% Nitrogen",
    description: "Mars is the fourth planet from the Sun, known as the Red Planet due to iron oxide (rust) on its surface. It has the tallest volcano and deepest canyon in the Solar System.",
    facts: [
      "Home to Olympus Mons — tallest volcano (21.9 km)",
      "Valles Marineris canyon is 4,000 km long",
      "Has polar ice caps made of water and CO₂ ice",
      "Dust storms can engulf the entire planet",
      "Two small moons: Phobos and Deimos",
      "Most explored planet after Earth",
    ],
    moons: 2,
    moonNames: ["Phobos", "Deimos"],
    hasRings: false,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "227.9 million km",
  },
  Jupiter: {
    name: "Jupiter",
    type: "Gas Giant",
    diameter: "139,820 km",
    mass: "1.898 × 10²⁷ kg",
    temperature: "-110°C (cloud top)",
    dayLength: "9 hours 56 minutes",
    yearLength: "11.86 Earth years",
    gravity: "24.79 m/s²",
    atmosphere: "89% Hydrogen, 10% Helium",
    description: "Jupiter is the largest planet in our Solar System — more than twice as massive as all other planets combined. Its Great Red Spot is a storm that has been raging for at least 400 years.",
    facts: [
      "Largest planet — could fit 1,300 Earths inside",
      "Great Red Spot is a storm larger than Earth",
      "Has at least 95 known moons",
      "Fastest rotating planet (10-hour day)",
      "Strong magnetic field — 20,000× Earth's",
      "Acts as a cosmic vacuum cleaner, deflecting asteroids",
    ],
    moons: 95,
    moonNames: ["Io", "Europa", "Ganymede", "Callisto", "+ 91 others"],
    hasRings: true,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "778.5 million km",
  },
  Saturn: {
    name: "Saturn",
    type: "Gas Giant",
    diameter: "116,460 km",
    mass: "5.683 × 10²⁶ kg",
    temperature: "-140°C (cloud top)",
    dayLength: "10 hours 42 minutes",
    yearLength: "29.46 Earth years",
    gravity: "10.44 m/s²",
    atmosphere: "96% Hydrogen, 3% Helium",
    description: "Saturn is the sixth planet from the Sun, famous for its spectacular ring system. The rings are made of billions of particles of ice and rock, ranging from tiny grains to house-sized chunks.",
    facts: [
      "Rings span 282,000 km but are only 10 meters thick",
      "Least dense planet — would float in water",
      "Has 146 known moons, including Titan",
      "Titan has a thick atmosphere and liquid methane lakes",
      "Wind speeds can reach 1,800 km/h",
      "Hexagonal storm pattern at its north pole",
    ],
    moons: 146,
    moonNames: ["Titan", "Enceladus", "Mimas", "Rhea", "+ 142 others"],
    hasRings: true,
    discoveredBy: "Known since antiquity",
    distanceFromSun: "1.434 billion km",
  },
  Uranus: {
    name: "Uranus",
    type: "Ice Giant",
    diameter: "50,724 km",
    mass: "8.681 × 10²⁵ kg",
    temperature: "-195°C (cloud top)",
    dayLength: "17 hours 14 minutes (retrograde)",
    yearLength: "84.01 Earth years",
    gravity: "8.87 m/s²",
    atmosphere: "83% Hydrogen, 15% Helium, 2% Methane",
    description: "Uranus is the seventh planet from the Sun. It's unique because it rotates on its side — its axial tilt is 98°. The methane in its atmosphere gives it a blue-green color.",
    facts: [
      "Rotates on its side (98° axial tilt)",
      "Coldest planetary atmosphere: -224°C",
      "Has 13 known rings (faint and dark)",
      "28 known moons named after Shakespeare characters",
      "Methane gives it the blue-green color",
      "Discovered in 1781 by William Herschel",
    ],
    moons: 28,
    moonNames: ["Titania", "Oberon", "Ariel", "Umbriel", "+ 24 others"],
    hasRings: true,
    discoveredBy: "William Herschel (1781)",
    distanceFromSun: "2.871 billion km",
  },
  Neptune: {
    name: "Neptune",
    type: "Ice Giant",
    diameter: "49,244 km",
    mass: "1.024 × 10²⁶ kg",
    temperature: "-200°C (cloud top)",
    dayLength: "16 hours 6 minutes",
    yearLength: "164.8 Earth years",
    gravity: "11.15 m/s²",
    atmosphere: "80% Hydrogen, 19% Helium, 1% Methane",
    description: "Neptune is the farthest planet from the Sun. It has the strongest winds in the Solar System, reaching speeds of 2,100 km/h. Its deep blue color comes from methane in the atmosphere.",
    facts: [
      "Farthest planet from the Sun",
      "Strongest winds in the Solar System (2,100 km/h)",
      "Has 16 known moons, largest is Triton",
      "Triton orbits backwards — likely a captured Kuiper Belt object",
      "Predicted mathematically before being observed",
      "Discovered in 1846 by Johann Galle",
    ],
    moons: 16,
    moonNames: ["Triton", "Nereid", "Proteus", "+ 13 others"],
    hasRings: true,
    discoveredBy: "Johann Galle (1846)",
    distanceFromSun: "4.495 billion km",
  },
  Pluto: {
    name: "Pluto",
    type: "Dwarf Planet",
    diameter: "2,377 km",
    mass: "1.303 × 10²² kg",
    temperature: "-230°C (average)",
    dayLength: "6.39 Earth days (retrograde)",
    yearLength: "248 Earth years",
    gravity: "0.62 m/s²",
    atmosphere: "Thin: Nitrogen, Methane, CO",
    description: "Pluto is a dwarf planet in the Kuiper Belt. Once considered the ninth planet, it was reclassified in 2006. NASA's New Horizons mission revealed a surprisingly complex and geologically active world.",
    facts: [
      "Reclassified as dwarf planet in 2006",
      "Has a heart-shaped nitrogen ice plain (Tombaugh Regio)",
      "5 known moons, largest is Charon",
      "Charon is so large it's almost a binary system",
      "Orbit is highly elliptical and tilted 17°",
      "Discovered in 1930 by Clyde Tombaugh",
    ],
    moons: 5,
    moonNames: ["Charon", "Nix", "Hydra", "Kerberos", "Styx"],
    hasRings: false,
    discoveredBy: "Clyde Tombaugh (1930)",
    distanceFromSun: "5.906 billion km",
  },
};

// ============================================
// COMPARISON DATA (for compare mode)
// ============================================
export const COMPARISON_METRICS = [
  { key: "diameter", label: "Diameter", unit: "km" },
  { key: "mass", label: "Mass", unit: "" },
  { key: "gravity", label: "Surface Gravity", unit: "m/s²" },
  { key: "temperature", label: "Temperature", unit: "" },
  { key: "dayLength", label: "Day Length", unit: "" },
  { key: "yearLength", label: "Year Length", unit: "" },
  { key: "moons", label: "Known Moons", unit: "" },
  { key: "distanceFromSun", label: "Distance from Sun", unit: "" },
];

// Numeric values for bar chart comparisons
export const COMPARISON_VALUES = {
  diameter: { Mercury: 4879, Venus: 12104, Earth: 12742, Mars: 6779, Jupiter: 139820, Saturn: 116460, Uranus: 50724, Neptune: 49244 },
  mass: { Mercury: 0.055, Venus: 0.815, Earth: 1, Mars: 0.107, Jupiter: 317.8, Saturn: 95.2, Uranus: 14.5, Neptune: 17.1 },
  gravity: { Mercury: 3.7, Venus: 8.87, Earth: 9.81, Mars: 3.72, Jupiter: 24.79, Saturn: 10.44, Uranus: 8.87, Neptune: 11.15 },
  moons: { Mercury: 0, Venus: 0, Earth: 1, Mars: 2, Jupiter: 95, Saturn: 146, Uranus: 28, Neptune: 16 },
  distanceAU: { Mercury: 0.387, Venus: 0.723, Earth: 1, Mars: 1.524, Jupiter: 5.203, Saturn: 9.537, Uranus: 19.19, Neptune: 30.07 },
};
